# Step 4.2 continued - Install Erlang & Elixir on bigsur

- hosts: localhost

  vars_prompt:
  - name: password
    prompt: What is your password?
    private: yes

  tasks:
  # to be run in app directory
  # not working: 'No such file or directory'
  - name: get current vesions
    ansible.builtin.shell: cat .tools-version
    # need to register current version data as variable to later access
    ignore_errors: yes

# Erlang
  - name: set env variable
    ansible.builtin.shell:  export KERL_CONFIGURE_OPTIONS="--without-javac --with-ssl=$(brew --prefix openssl)"

  # failed - syntax error
  # went to link and copied install. Difference - removed angle brackets
  # failed - new failure, plugin named erlang already added
  - name: add erlang plugin to asdf
    ansible.builtin.shell: asdf plugin add erlang https://github.com/asdf-vm/asdf-erlang.git
    ignore_errors: yes

  # failed - asdf_22.3 is not a kerl-managed Erlang/OTP installation
  # 22.3.1 is the earliest version that can be installed through kerl/asdf.
  # changed 22.3 --> 22.3.1 (don't do it need 22.3. Also, doesn't work)
  # Big Sur causing massive issue
  # brew uninstall autoconf and install autoconf2.69 - https://github.com/asdf-vm/asdf-erlang/issues/195#issuecomment-815999279
    # brew uninstall autoconf
    # curl -O http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
    # tar zxvf autoconf-2.69.tar.gz
    # cd autoconf-2.69
    # ./configure && make && sudo make install
    # asdf install erlang 22.3
    
  - name: erlang install
    ansible.builtin.shell: asdf install erlang 22.3
    register: erlanginstall
    ignore_errors: yes

  - name: elixir install
    ansible.builtin.shell: asdf install elixir 1.10.3
    register: elixirinstall
    ignore_errors: yes

  - name: list all erlang
    ansible.builtin.shell: asdf list-all erlang