- hosts: localhost

  vars_prompt:
  - name: password
    prompt: What is your password?
    private: yes

  tasks:
  - name: Start dev environment installation
    ansible.builtin.debug:
      msg: Developer environment installation has started.

  - name: Update ansible playbook
    ansible.builtin.shell: git pull
    register: pull

  - name: Check if Homebrew is already installed
    stat:
      path: /usr/local/bin/brew
    register: b

  - name: Update recipes and run brew doctor to fix any issues
    ansible.builtin.shell: brew update && brew doctor
    register: brewdoc
    when: b.stat.exists
    failed_when: "'Error' in brewdoc.stderr"

  - name: Install redis mysql56 memcached ImageMagick git openssl gpg autoconf
    ansible.builtin.shell: brew install redis mysql56 memcached ImageMagick git openssl gpg autoconf
    register: brewinstall
    when: b.stat.exists
    failed_when: "'Error' in brewinstall.stderr"

  - name: Access mongodb repo
    ansible.builtin.shell: brew tap mongodb/brew
    register: brewinstall2
    when: b.stat.exists
    failed_when: "'Error' in brewinstall2.stderr"

  - name: Install mongodb-community@4.2
    ansible.builtin.shell: brew install mongodb-community@4.2
    register: brewinstall3
    when: b.stat.exists
    failed_when: "'Error' in brewinstall3.stderr"

  - name: Link mysql 5.6
    ansible.builtin.shell: brew link mysql56
    register: linkmysql56
    when: b.stat.exists
    failed_when: "'Error' in linkmysql56.stderr"

  - name: Clone asdf
    ansible.builtin.shell: git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.1
    register: cloneasdf
    failed_when: "'Error' in cloneasdf.stderr"

  - name: echo '\n. $HOME/.asdf/asdf.sh' >> ~/.bash_profile
    ansible.builtin.shell: echo '\n. $HOME/.asdf/asdf.sh' >> ~/.bash_profile
    register: bashasdfsh

  - name: echo '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bash_profile
    ansible.builtin.shell: echo '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bash_profile
    register: bashasdfbash

  - name: source ~/.bash_profile
    ansible.builtin.shell: source ~/.bash_profile
    register: bash_profile

  - name: echo '\nautoload -U +X compinit && compinit' >> ~/.zshrc
    ansible.builtin.shell: echo '\nautoload -U +X compinit && compinit' >> ~/.zshrc
    register: zshautoload

  - name: echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.zshrc
    ansible.builtin.shell: echo '\n. $HOME/.asdf/asdf.sh' >> ~/.zshrc
    register: zshasdfsh

  - name: echo '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.zshrc
    ansible.builtin.shell: echo '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.zshrc
    register: zshasdfbash

  - name: source ~/.zshrc
    ansible.builtin.shell: source ~/.zshrc
    register: zshrc
  
  - name: mkdir -p ~/.config/fish/ && touch ~/.config/fish/config.fish
    ansible.builtin.shell: mkdir -p ~/.config/fish/ && touch ~/.config/fish/config.fish
    register: mkdir_configfish

  - name: echo 'source ~/.asdf/asdf.fish' >> ~/.config/fish/config.fish
    ansible.builtin.shell: echo 'source ~/.asdf/asdf.fish' >> ~/.config/fish/config.fish
    register: config_fish

  - name: mkdir -p ~/.config/fish/completions && cp ~/.asdf/completions/asdf.fish ~/.config/fish/completions
    ansible.builtin.shell: mkdir -p ~/.config/fish/completions && cp ~/.asdf/completions/asdf.fish ~/.config/fish/completions
    register: mkdir_fish

  - name: echo 'source "(brew --prefix asdf)"/asdf.fish' >> ~/.c
    ansible.builtin.shell: echo 'source "(brew --prefix asdf)"/asdf.fish' >> ~/.c
    register: fish

  - name: Add node-js plugin to asdf
    ansible.builtin.shell: asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
    register: nodeasdf
    failed_when: "'Error' in nodeasdf.stderr"

  - name: Override authenticity check
    ansible.builtin.shell: NODEJS_CHECK_SIGNATURES=no asdf install nodejs 12.16.3
    register: checknodejs

  - name: asdf install nodejs 12.16.3
    ansible.builtin.shell: asdf install nodejs 12.16.3
    register: installnodejs

  - name: asdf global nodejs 12.16.3
    ansible.builtin.shell: asdf global nodejs 12.16.3
    register: globalnodejs

  - name: npm install -g yarn
    ansible.builtin.shell: npm install -g yarn
    register: installyarn

  - name: yarn set version latest
    ansible.builtin.shell: yarn set version latest
    register: installyarn

  - name: asdf install
    ansible.builtin.shell: asdf install
    register: asdfinstall
  
  - name: brew install wget
    ansible.builtin.shell: brew install wget
    register: installwget

  - name: asdf plugin-add ruby
    ansible.builtin.shell: asdf plugin-add ruby
    register: rubyplugin
    failed_when: "'Error' in rubyplugin.stderr"

  - name: asdf install ruby 2.3.6
    ansible.builtin.shell: asdf install ruby 2.3.6
    register: rubyinstall

  - name: asdf global ruby 2.3.6
    ansible.builtin.shell: asdf global ruby 2.3.6
    register: golbalruby