# step 11: install Rails and gems for TAS app
- hosts: localhost

  tasks: 
  # Configure Bundler Build Options to prevent problems with installing gems
  # ref: https://bundler.io/man/bundle-config.1.html#BUILD-OPTIONS
  - name: build libv8
    ansible.builtin.shell: bundle config --global build.libv8 --with-system-v8

  - name: build therubyracer
    ansible.builtin.shell: bundle config --global build.therubyracer --with-v8-dir=/usr/local/opt/v8@3.15 --with-openssl-dir=/usr/local/opt/openssl@1.1
  
  - name: build mysql2
    ansible.builtin.shell: bundle config --global build.mysql2 --with-opt-dir=/usr/local/opt/openssl@1.1
  
  - name: build ffi
    ansible.builtin.shell: bundle config --global build.ffi --with-cflags="-Wno-error=implicit-function-declaration"
  
  - name: build thin
    ansible.builtin.shell: bundle config --global build.thin --with-cflags="-Wno-error=implicit-function-declaration"
  
  - name: build event machine
    ansible.builtin.shell: bundle config --global build.eventmachine --with-cppflags="-I/usr/local/opt/openssl@1.1/include"
  
  # install rails and gems for your repos
  - name: cd to repo
    ansible.builtin.shell: cd ~/Documents/tdoc/telapp/tas # e.g. telapp/tas

  # Could not verify the SSL certificate
  # solution - https://confluence.teladoc.net/display/TDOC/Developer+Machine+Setup#DeveloperMachineSetup-1.RubySSLError(LibreSSL/OpenSSL)
  - name: openssl version
    ansible.builtin.shell: openssl version
    register: opensslversion

  - name: print openssl version
    ansible.builtin.debug: 
      msg: openssl version {{ opensslversion.stdout_lines }}

  # for LibreSSL version 2.*
  - name: for libreSSL version 2.* (brew install)
    ansible.builtin.shell: brew install libressl
    when: opensslversion.stdout_lines is match("\\['LibreSSL 2.")

  - name: for libreSSL version 2.* (ln -sf)
    ansible.builtin.shell: ln -sf /usr/local/etc/libressl/cert.pem ~/.asdf/installs/ruby/2.3.6/openssl/ssl/cert.pem
    when: opensslversion.stdout_lines is match("\\['LibreSSL 2.")

  # for LibreSSL version 3.*
  - name: for LibreSSL version 3.* (brew upgrade)
    ansible.builtin.shell: brew upgrade libressl
    when: opensslversion.stdout_lines is match("\\['libreSSL 3.")

  - name: for LibreSSL version 3.* (ln -sf)
    ansible.builtin.shell: ln -sf /usr/local/etc/libressl/cert.pem ~/.asdf/installs/ruby/2.3.6/openssl/ssl/cert.pem
    when: opensslversion.stdout_lines is match("\\['libreSSL 3.")
  
  - name: bundle install
    ansible.builtin.shell: bundle install

  # ~/Users/michael.le/Documents/projetdoccts/telapp/tas