# step 11: install Rails and gems for TAS app
- hosts: localhost

  tasks: 
  # Configure Bundler Build Options to prevent problems with installing gems
  # ref: https://bundler.io/man/bundle-config.1.html#BUILD-OPTIONS
  - name: build libv8
    ansible.builtin.shell: bundle config --global build.libv8 --with-system-v8

  - name: build therubyracer
    ansible.builtin.shell: bundle config --global build.therubyracer --with-v8-dir=/usr/local/opt/v8@3.15 --with-openssl-dir=/usr/local/opt/openssl@1.1
  
  - name: build mysql2
    ansible.builtin.shell: bundle config --global build.mysql2 --with-opt-dir=/usr/local/opt/openssl@1.1
  
  - name: build ffi
    ansible.builtin.shell: bundle config --global build.ffi --with-cflags="-Wno-error=implicit-function-declaration"
  
  - name: build thin
    ansible.builtin.shell: bundle config --global build.thin --with-cflags="-Wno-error=implicit-function-declaration"
  
  - name: build event machine
    ansible.builtin.shell: bundle config --global build.eventmachine --with-cppflags="-I/usr/local/opt/openssl@1.1/include"
  
  # install rails and gems for your repos
  - name: cd to repo
    ansible.builtin.shell: cd ~/Documents/tdoc/telapp/tas

  # where am I? pwd
  - name: get directory
    ansible.builtin.shell: pwd
    register: iamhere

  - name: print iamhere
    ansible.builtin.debug:
      msg: I am here {{ iamhere.stdout_lines }}

  # Could not verify the SSL certificate
  # solution - https://confluence.teladoc.net/display/TDOC/Developer+Machine+Setup#DeveloperMachineSetup-1.RubySSLError(LibreSSL/OpenSSL)
  - name: openssl version
    ansible.builtin.shell: openssl version
    register: opensslversion

  - name: print openssl version
    ansible.builtin.debug: 
      msg: openssl version {{ opensslversion.stdout_lines }}

  # for LibreSSL version 2.*
  - name: for libreSSL version 2.* (brew install)
    ansible.builtin.shell: brew install libressl
    when: opensslversion.stdout_lines is match("\\['LibreSSL 2.")

  - name: for libreSSL version 2.* (ln -sf)
    ansible.builtin.shell: ln -sf /usr/local/etc/libressl/cert.pem ~/.asdf/installs/ruby/2.3.6/openssl/ssl/cert.pem
    when: opensslversion.stdout_lines is match("\\['LibreSSL 2.")

  # for LibreSSL version 3.*
  - name: for LibreSSL version 3.* (brew upgrade)
    ansible.builtin.shell: brew upgrade libressl
    when: opensslversion.stdout_lines is match("\\['LibreSSL 3.")

  - name: for LibreSSL version 3.* (ln -sf)
    ansible.builtin.shell: ln -sf /usr/local/etc/libressl/cert.pem ~/.asdf/installs/ruby/2.3.6/openssl/ssl/cert.pem
    when: opensslversion.stdout_lines is match("\\['LibreSSL 3.")
  
  # for OpenSSL version 1.1*
  - name: for openssl version 1.1* (brew upgrade openssl@1.1)
    ansible.builtin.shell: brew upgrade openssl@1.1
    when: opensslversion.stdout_lines is match("\\['OpenSSL 1.1")

  - name: for openssl version 1.1* (ln -sf)
    ansible.builtin.shell: ln -sf /usr/local/etc/ca-certificates/cert.pem ~/.asdf/installs/ruby/2.3.6/openssl/ssl/cert.pem
    when: opensslversion.stdout_lines is match("\\['OpenSSL 1.1")

  # for OpenSSL version 3.*
  - name: for OpenSSL version 3.* (brew upgrade openssl@3)
    ansible.builtin.shell: brew upgrade openssl@3
    when: opensslversion.stdout_lines is match("\\['OpenSSL 3.")

  - name: for OpenSSL version 3.* (ln -sf)
    ansible.builtin.shell: ln -sf /usr/local/etc/openssl@3/cert.pem ~/.asdf/installs/ruby/2.3.6/openssl/ssl/cert.pem
    when: opensslversion.stdout_lines is match("\\['OpenSSL 3.")

  - name: print iamhere
    ansible.builtin.debug:
      msg: I am here {{ iamhere.stdout_lines }}

  - name: bundle install
    ansible.builtin.shell: bundle install
    args:
      # chdir will change to this directory before running command
      chdir: ~/Documents/tdoc/telapp/tas

  # ~/Users/michael.le/Documents/projetdoccts/telapp/tas
  # error, not in right directory

  # use this to search for where telapp/tas is
  # find <directory> -wholename <repo>