# Step 9: Update RubyGems and Install Bundler
- hosts: localhost

  vars_prompt:
  - name: password
    prompt: what is your password?
    private: yes

  tasks:
  - name: RubyGems update
    ansible.builtin.shell: gem update --system
    register: rubygemsupdate

  - name: bundler install
    ansible.builtin.shell: gem install bundler -v 1.17.3
    register: bundlerinstall